version: "3"

vars:
  RUST_DIR: rust-modules
  TARGET_DIR: "{{.RUST_DIR}}/target/release"
  CONFIG_SRC: config-src
  STYLES_SRC: styles
  BUILD_DIR: target
  INSTALL_DIR: ~/.config/waybar

tasks:
  default:
    desc: Build everything (Rust + configs + styles)
    cmds:
      - task: build-rust
      - task: build-config
      - task: build-styles
      - echo "✓ All builds complete. Output in {{.BUILD_DIR}}/"

  build-rust:
    desc: Compile all Rust binaries in release mode
    dir: "{{.RUST_DIR}}"
    cmds:
      - echo "Building Rust workspace..."
      - cargo build --release
      - echo "✓ Rust binaries built in {{.TARGET_DIR}}"
    sources:
      - "**/*.rs"
      - "**/Cargo.toml"
    generates:
      - "{{.TARGET_DIR}}/sys-monitor"
      - "{{.TARGET_DIR}}/netspeed"
      - "{{.TARGET_DIR}}/gpu-monitor"
      - "{{.TARGET_DIR}}/mpris-control"
      - "{{.TARGET_DIR}}/privacy-monitor"
      - "{{.TARGET_DIR}}/weather-fetch"
      - "{{.TARGET_DIR}}/net-quality"
      - "{{.TARGET_DIR}}/vpn-manager"
      - "{{.TARGET_DIR}}/bluetooth-mgr"
      - "{{.TARGET_DIR}}/clipboard-mgr"
      - "{{.TARGET_DIR}}/updates-monitor"
      - "{{.TARGET_DIR}}/audio-viz"
      - "{{.TARGET_DIR}}/app-volume-mixer"
      - "{{.TARGET_DIR}}/theme-switcher"
      - "{{.TARGET_DIR}}/waybar-daemon"

  build-config:
    desc: Merge modular JSON configs into single Waybar config
    cmds:
      - echo "Building config..."
      - task: merge-config
      - task: validate-config

  merge-config:
    desc: Merge JSON module files
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - ./scripts/merge-configs.sh {{.BUILD_DIR}}/config
    sources:
      - "{{.CONFIG_SRC}}/**/*.json"
    generates:
      - "{{.BUILD_DIR}}/config"

  validate-config:
    desc: Validate generated config
    cmds:
      - echo "Validating config..."
      - |
        if [ -f {{.BUILD_DIR}}/config ]; then
          if command -v jq &> /dev/null; then
            jq empty {{.BUILD_DIR}}/config && echo "✓ Config is valid JSON"
          else
            echo "⚠ jq not found, skipping validation"
          fi
        fi

  build-styles:
    desc: Copy GTK CSS styles (Waybar uses GTK CSS, not SASS)
    cmds:
      - echo "Building styles..."
      - mkdir -p {{.BUILD_DIR}}
      - cp {{.STYLES_SRC}}/main.css {{.BUILD_DIR}}/style.css
      - echo "✓ Styles copied (GTK CSS format)"
    sources:
      - "{{.STYLES_SRC}}/**/*.css"
    generates:
      - "{{.BUILD_DIR}}/style.css"

  install:
    desc: Build and deploy everything to ~/.config/waybar
    cmds:
      - task: default
      - task: deploy

  deploy:
    desc: Deploy built files to ~/.config/waybar and reload Waybar
    cmds:
      - task: verify-build
      - task: backup-configs
      - task: copy-configs
      - task: reload-waybar
      - task: show-status

  verify-build:
    desc: Verify build artifacts exist
    internal: true
    cmds:
      - |
        echo "📦 Verifying build artifacts..."
        if [ ! -f {{.BUILD_DIR}}/config ]; then
          echo "❌ Error: Build artifacts not found. Run 'task default' first."
          exit 1
        fi
        # Count binaries
        BINS_FOUND=$(ls {{.TARGET_DIR}}/*-monitor {{.TARGET_DIR}}/netspeed {{.TARGET_DIR}}/theme-switcher {{.TARGET_DIR}}/*-mgr {{.TARGET_DIR}}/*-quality {{.TARGET_DIR}}/*-fetch {{.TARGET_DIR}}/*-viz 2>/dev/null | wc -l)
        echo "✓ Found build artifacts ($BINS_FOUND binaries ready)"

  backup-configs:
    desc: Backup existing config and styles
    internal: true
    cmds:
      - |
        echo "💾 Backing up existing files..."
        mkdir -p {{.INSTALL_DIR}}
        TIMESTAMP=$(date +%s)
        # Backup config if it exists and is not a symlink
        if [ -f {{.INSTALL_DIR}}/config ] && [ ! -L {{.INSTALL_DIR}}/config ]; then
          cp {{.INSTALL_DIR}}/config {{.INSTALL_DIR}}/config.backup-$TIMESTAMP
          echo "  ✓ Backed up config"
        fi
        # Backup style.css if it exists and is not a symlink
        if [ -f {{.INSTALL_DIR}}/style.css ] && [ ! -L {{.INSTALL_DIR}}/style.css ]; then
          cp {{.INSTALL_DIR}}/style.css {{.INSTALL_DIR}}/style.css.backup-$TIMESTAMP
          echo "  ✓ Backed up style.css"
        fi

  copy-configs:
    desc: Copy config and styles to install directory
    internal: true
    cmds:
      - |
        echo "📋 Installing files..."
        cp {{.BUILD_DIR}}/config {{.INSTALL_DIR}}/config
        echo "  ✓ Config installed"
        cp {{.BUILD_DIR}}/style.css {{.INSTALL_DIR}}/style.css
        echo "  ✓ Styles installed"

  reload-waybar:
    desc: Restart or reload Waybar
    internal: true
    cmds:
      - |
        echo "🔄 Reloading Waybar..."
        if pgrep -x waybar > /dev/null; then
          # Try graceful reload first
          if pkill -SIGUSR2 waybar 2>/dev/null; then
            echo "  ✓ Waybar reloaded gracefully"
          else
            # Fallback to hard restart
            killall waybar 2>/dev/null || true
            sleep 0.5
            waybar &>/dev/null &
            disown 2>/dev/null || true
            echo "  ✓ Waybar restarted"
          fi
        else
          # Start Waybar if not running
          waybar &>/dev/null &
          disown 2>/dev/null || true
          echo "  ✓ Waybar started"
        fi

  show-status:
    desc: Show deployment status
    internal: true
    cmds:
      - |
        echo ""
        echo "✅ Deployment complete!"
        echo ""
        echo "📍 Locations:"
        echo "   Config:   {{.INSTALL_DIR}}/config"
        echo "   Styles:   {{.INSTALL_DIR}}/style.css"
        echo "   Binaries: {{.TARGET_DIR}}/"
        echo ""

  clean:
    desc: Clean all build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - cd {{.RUST_DIR}} && cargo clean
      - echo "✓ Cleaned all build artifacts"

  dev:
    desc: Build and test a specific module
    cmds:
      - echo "Usage - task dev-module MODULE=sys-monitor"

  dev-module:
    desc: Build and test a specific Rust module
    dir: "{{.RUST_DIR}}"
    cmds:
      - cargo build --release -p {{.MODULE}}
      - echo "✓ Built {{.MODULE}}"
      - "{{.TARGET_DIR}}/{{.MODULE}}"

  test:
    desc: Test all monitoring binaries
    cmds:
      - task: build-rust
      - echo "Testing binaries..."
      - "{{.TARGET_DIR}}/sys-monitor all || true"
      - "{{.TARGET_DIR}}/netspeed || true"
      - "{{.TARGET_DIR}}/gpu-monitor || true"
      - echo "✓ Tests complete"

  check:
    desc: Check Rust code without building
    dir: "{{.RUST_DIR}}"
    cmds:
      - cargo check --workspace

  fmt:
    desc: Format Rust code
    dir: "{{.RUST_DIR}}"
    cmds:
      - cargo fmt --all

  clippy:
    desc: Run clippy lints
    dir: "{{.RUST_DIR}}"
    cmds:
      - cargo clippy --workspace --all-targets

  watch:
    desc: Watch for changes and auto-rebuild
    cmds:
      - ./scripts/watch-mode.sh
